---
apiVersion: v2
appVersion: 1.13.1
description: A Helm umbrella chart for Vault
name: vault
home: https://www.vaultproject.io
icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
type: application
version: 0.24.1
dependencies:
  - name: vault
    version: "0.24.1"
    repository: "https://helm.releases.hashicorp.com"
